version: '3'

services:

  app:
    build: .
    container_name: micro-videos-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: micro-videos-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8010:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0
    container_name: micro-videos-db
    restart: unless-stopped
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: micro-videos-redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
